### ISSUE TITLE
Negative rack.request.queue.time

### ISSUE THREAD

**Issue by austinthecoder** [librato/librato-rack#66]
Sometimes the `rack.request.queue.time` metric is negative. I suppose this happens when `env['HTTP_X_REQUEST_START']` or `env['HTTP_X_QUEUE_START']` is in the future.

Would it make sense to set it to 0 if it's negative? That is precisely what heroku/rack-timeout does:

https://github.com/heroku/rack-timeout/blob/master/lib/rack/timeout/core.rb#L91

They do this to "make up for potential time drift between the routing server and the application server".

I'll gladly submit a PR if you agree. 😄

**Comment by chancefeick** [comment]
Thanks for opening the issue, @austinthecoder.

This is most likely a scenario that we haven't encountered as a result of setting the minimum value to zero in chart attributes. Your suggestion makes sense to me to handle a potential time drift 👍

**Comment by chancefeick** [comment]
Released in 2.0.1.
